FROM node:16

LABEL maintainer="xyzsince2014 <xyzsince2014@gmail.com>"

ARG PORT
ARG DB_HOST
ARG DB_DATABASE
ARG DB_USER
ARG DB_PASSWORD
ARG DB_PORT
ARG AUTH_CONTAINER

ENV PORT=${PORT}
ENV DB_HOST=${DB_HOST}
ENV DB_DATABASE=${DB_DATABASE}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_PORT=${DB_PORT}
ENV AUTH_CONTAINER=${AUTH_CONTAINER}

RUN mkdir /src
COPY . /src

WORKDIR /src

RUN yarn install --production

ENTRYPOINT [ "yarn", "start" ]
